version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps:
          dependency-file: test_requirements.txt
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
